name: basic_fastapi_ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
env:
  PORT: ${{ secrets.PORT }}
jobs:
  test:
        environment: test_env
        env:
          PORT: ${{ secrets.PORT }}
          PASSWORD: 'taknavazan'
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.10'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
            - name: unit test
              run: |
                  echo 'running test'  
                  pytest -v
                  echo 'test completed'
            - name: uploading artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: artifact.txt
            - name: printing envs
              run: |
                echo 'PORT: ${{env.PORT}}'
                echo 'PASSWORD: ${{env.PASSWORD}}'
  
  build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
            - name: building project
              run: |
                  echo "Building project"
            - name: printing envs
              run: |
                echo 'PORT: ${{env.PORT}}'
                echo 'PASSWORD: ${{env.PASSWORD}}'
    
  run:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt 
            - name: building project
              run: |
                  echo "Building project"

  deploy:
        strategy:
          matrix:
            opeartion-system: [windows-latest, ubuntu-latest]
            python-version: ['3.10', '3.11', '3.12']
            include:
              - opeartion-system: ubuntu-latest
                python-version: '3.13'
            exclude:
              - opeartion-system: windows-latest
                python-version: '3.10'
        runs-on: ubuntu-latest
        needs: run
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt 
            - name: building project
              run: |
                  echo "Building project"
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: my-artifact
  nokhodi:
        runs-on: ubuntu-latest
        needs: test
        if: always()
        steps:
            - name: printing ok
              run: |
                  echo "ok"
  mamdaliof:
        runs-on: ubuntu-latest
        env: 
          X: ${{ secrets.SECRET_X }}
          Y: ${{ secrets.SECRET_Y }}
        steps:
          - name: check secret
            run : |
              if [ "$X" == "2" ] || [ "$Y" == "2" ]; then
                echo "Secrets are both 2. Proceeding..."
              else
                echo "Secrets are not both 2. Failing the job."
                exit 1
              fi     


        